on:
 workflow_dispatch:
 schedule:
   - cron: 30 * * * *
 pull_request:
   types: [opened, synchronize, reopened, closed]
name: Build + compile
jobs:
 echo: 
   name: Echo github context
   runs-on: ubuntu-latest
   steps:
     - run: echo "${{ !(github.actor == 'Explosion-Scratch' && github.event.pull_request) }}"
     - run: echo "Github actor is Explosion-Scratch? ${{ github.actor == 'Explosion-Scratch' }}"
     - run: echo "Is PR? ${{ !!github.event.pull_request }}"
     - run: echo "PR author â€“ ${{github.event.pull_request.user.login}}"
 release:
   name: Build + compile
   runs-on: ubuntu-latest
   if: github.actor != 'Explosion-Scratch' || !github.event.pull_request || github.event.pull_request.user.login != 'Explosion-Scratch'
   steps:
     - name: Build and compile
       uses: technote-space/create-pr-action@v2
       with:
         GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN || github.token}}
         EXECUTE_COMMANDS: |
           sudo npm install;
           sudo npm i -g eslint
           sudo npm i -g prettier
           sudo npm i -g terser
           sudo npm i -g jsdoc
           sudo npm i -g rollup
           sudo npm i -g figlet-cli
           sudo npm i -g jsdoc-to-markdown
           rm -f bijou_node.js
           rm -f bijou.js
           cat ./js/_copyright.js ./js/array.js ./js/color.js ./js/date.js ./js/element.js ./js/event.js ./js/function.js ./js/object.js ./js/math.js ./js/string.js ./js/utility.js ./js/_end.js > bijou.js
           rm -rf docs/docs
           rm -f bijou-min.js
           jsdoc -c jsdoc.json
           sudo eslint --fix ./ || eslint --fix ./ || ls
           prettier --write -- .
           rollup bijou.js --file bijou_node.js --format cjs
           terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o docs/bijou.js -- bijou.js
           terser --comments false --ecma 6 --ie8 --module --compress --drop-console --mangle -o bijou-min.js -- bijou.js
           jsdoc2md bijou.js > documentation.md
         COMMIT_MESSAGE: "Automated build"
         COMMIT_NAME: 'Explosion-Scratch'
         COMMIT_EMAIL: 'explosionscratch@gmail.com'
         PR_BRANCH_NAME: 'build-pr-${PR_NUMBER}'
         PR_TITLE: 'Build and compile ${PR_NUMBER_REF}'
