on: push
name: Generate docs
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<HEAD>>>>>>>>>>>>>>>>>>>>>>>>>>>
jobs:
 git-bat:
    if: "contains(github.event.head_commit.message, '[Docs]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: sudo npm install --save 
      - run: npm run doc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: Docs Generated

        
